#!/bin/bash


source .env

docker context use default

docker build -t $NAME:latest --build-arg="MONGO_VERSION=$MONGO_VERSION" .

for TAG in ${TAGS[@]}; do
    docker tag $NAME:latest $NAME:$TAG
done

docker push $NAME --all-tags
